# Generated by Django 3.2.6 on 2022-01-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='file_uploaded',
            field=models.FileField(default='NONE', upload_to='FILES'),
            preserve_default=False,
        ),
    ]
